title: Standard-Seite

navigation:
  status: all
  template: all

tabs:
  content:
    label: Inhalt
    icon: page
    sections:
      fields:
        fields:
          text:
            extends: fields/blocks
  meta:
    label: Meta
    icon: search
    sections:
      metaFields:
        type: fields
        fields:
          metaDescription:
            extends: fields/meta-description
  pages:
    label: Unterseiten
    icon: list-bullet
    sections:
      pages:
        label: Unterseiten
        type: pages
  files:
    label: Dateien
    icon: file
    sections:
      files:
        label: Dateien
        type: files
