title: Standard-Seite

navigation:
  status: all
  template: all

options:
  changeTemplate:
    - info

tabs:
  content:
    extends: tabs/content
    sections:
      fields:
        fields:
          text:
            extends: fields/blocks
  meta:
    extends: tabs/meta
  pages:
    extends: tabs/subpages
  files:
    extends: tabs/files
