title: Info-Seite

navigation:
  status: all
  template: all
  sortBy: startDate desc

image:
  query: model.teaserImage.toFile
  cover: true

tabs:
  content:
    label: Inhalt
    icon: page
    sections:
      fields:
        fields:
          alternativeTitle:
            label: Teaser-Text
            extends: fields/writer-inline
            marks: false
          startDate:
            label: Start-Datum
            type: date
            width: 1/4
            help: Wird genutzt, damit auf den Leistungen-Seiten die neusten Projekte angezeigt werden können.
          period:
            label: field.period
            type: text
            width: 1/4
          location:
            label: field.location
            type: text
            width: 1/4
          areas_of_action:
            label: field.areas_of_action
            type: text
            width: 1/4
          partner:
            label: field.partner
            type: text
            width: 3/4
          servicePages:
            label: Zielgruppe
            type: pages
            query: site.servicesPage.childrenAndDrafts
            width: 1/4
          teaserText:
            label: Teaser-Text
            extends: fields/writer-inline
            width: 1/2
          teaserImage:
            extends: fields/teaser-image
            width: 1/4
          text:
            extends: fields/blocks
  meta:
    label: Meta
    icon: search
    sections:
      metaFields:
        type: fields
        fields:
          metaDescription:
            extends: fields/meta-description
  pages:
    label: Unterseiten
    icon: list-bullet
    sections:
      pages:
        label: Unterseiten
        type: pages
  files:
    label: Dateien
    icon: file
    sections:
      files:
        label: Dateien
        type: files
